version: 1.0.{build}
configuration: Release
platform:
- Win32
- x64
init:
- ps: 
install:
- ps: >-
    Push-Location "Quetoo.vs15\"

    [Environment]::CurrentDirectory = $PWD

    .\PREPARE_ALL.ps1

    Pop-Location

    [Environment]::CurrentDirectory = $PWD

    md -Path "..\Objectively"

    Push-Location "..\Objectively\"

    [Environment]::CurrentDirectory = $PWD

    (New-Object System.Net.WebClient).DownloadFile("https://ci.appveyor.com/api/projects/Paril/objectively/artifacts/__dep.zip?job=Platform%3A+" + $env:PLATFORM, "tmp.zip")

    7z x tmp.zip -aos "*"

    Remove-Item "tmp.*"

    Pop-Location

    [Environment]::CurrentDirectory = $PWD

    md -Path "..\ObjectivelyMVC"

    Push-Location "..\ObjectivelyMVC\"

    [Environment]::CurrentDirectory = $PWD

    (New-Object System.Net.WebClient).DownloadFile("https://ci.appveyor.com/api/projects/Paril/objectivelymvc/artifacts/__dep.zip?job=Platform%3A+" + $env:PLATFORM, "tmp.zip")

    7z x tmp.zip -aos "*"

    Remove-Item "tmp.*"

    Pop-Location

    [Environment]::CurrentDirectory = $PWD
build:
  parallel: false
  verbosity: minimal
test: off
deploy: off